### ISSUE TITLE
cannot access "raw.githubusercontent.com", the app will stop.

### ISSUE THREAD

**Issue by niyari** [frozenpandaman/splatnet2statink#100]
https://github.com/frozenpandaman/splatnet2statink/blob/d59c0466acf1df8e9aad17b5a8f97e7d90f33b6d/splatnet2statink.py#L223

**Comment by frozenpandaman** [comment]
Hmm, I guess hardcoding URLs to do this sort-of-hacky thing isn't that great in retrospect… and it's not like weapons are still being added to the game, though this was helpful at the time… but the URL works fine for me and the script runs fine. What error are you getting?

**Comment by frozenpandaman** [comment]
Also congrats on issue #100! 🎉😛

**Comment by niyari** [comment]
This issue occurs when NSO and statink are working fine and raw.githubusercontent.com is not working properly.
(HTTP 50x,40x...error. or network error on computer side.)
When the program gets the latest code on github and compares the versions, an error occurs because the character string cannot be extracted.
When the phenomenon appeared at me, I was temporarily commenting out the version check and dealing with it.

![example](https://user-images.githubusercontent.com/2970321/81006393-6c30f400-8e8a-11ea-93ec-548aa4518783.png)

This is a reproduced image that intentionally caused github to make an error.

**Comment by frozenpandaman** [comment]
Ahh, oops – that makes sense, yeah, in the case GitHub is down (or your internet is out, or something). The try statement should be around the whole thing, including that first call to the URL. 😅

I don't think it warrants a version bump, but now fixed in 2ad29c7! Thanks!
