### ISSUE TITLE
monitoring mode causing exception

### ISSUE THREAD

**Issue by Link8451** [frozenpandaman/splatnet2statink#103]
i set the monitoring mode to check every 5 min and when it finds a match an exception occurs which causes a cascade of other exceptions 
![image](https://user-images.githubusercontent.com/40288663/84603454-d060b380-ae4b-11ea-8e68-6a2db57f0989.png)
![image](https://user-images.githubusercontent.com/40288663/84603462-ea01fb00-ae4b-11ea-92b6-1018eb8030bc.png)

**Comment by Link8451** [comment]
i found that it only seems to happen if i go out of focus from the powershell window

**Comment by frozenpandaman** [comment]
This seems to be a PowerShell-specific issue, then, or something to do with your setup, where if it loses focus it interrupts a web connection request. This is working fine for me, i.e. I can confirm app.splatoon2.nintendo.net is not down or anything.
