### ISSUE TITLE
error from the flapg API

### ISSUE THREAD

**Issue by MonsieurA-SP** [frozenpandaman/splatnet2statink#108]
Hi!

The Windows version used to work fine, but now I have this.

> splatnet2statink v1.5.6
> Blank cookie.
> Attempting to generate new cookie...
> Error from the flapg API:
> {
>   "error": "Nintendo Switch Onlineアプリの更新によりログインできません"
> }

Thanks a lot for your work and hope you'll be able to solve this !

**Comment by frozenpandaman** [comment]
Might just be temporarily down. How long has this been happening? Try again later, and if this is still occurring in a day or two then let me know here.

**Comment by MonsieurA-SP** [comment]
Thank you for your answer.
It's been happening since last night.
I will try again later.

**Comment by radsutton** [comment]
Hi.
I've also had the same issue.

**Comment by frozenpandaman** [comment]
Hah, sorry, left that last comment hastily and pretty late at night without reading the error message in full… the flapg API's Android server needs to have its version of the NSO app updated (this was why s2s updated a couple days ago as well, #106). I assume NexusMine will get to this shortly!

**Comment by radsutton** [comment]
OK, thanks for the speedy answer! Hope so!

**Comment by rinsuki** [comment]
looks fixed?

```
$ ./splatnet2statink.py -r -M 600          
splatnet2statink v1.5.6
The stored cookie has expired.
Attempting to generate new cookie...
Wrote iksm_session cookie for り to config.txt.
Checking if there are previously-unuploaded battles...
```

**Comment by ofiala-a51** [comment]
Can confirm, issue is fixed.

**Comment by frozenpandaman** [comment]
Yay! I'm glad. Thanks for the update. :)
