### ISSUE TITLE
Automatic cookie creation is broken

### ISSUE THREAD

**Issue by Jasper128** [frozenpandaman/splatnet2statink#109]
I updated to v1.5.6 recently and now it will no longer try to create cookies automatically.
It says it is attempting to try to generate the cookie, but it immediately stops and doesn't generate one.
So the command is repeated again and it seems to fail, but it doesn't give out an error. Looks like this:

`PS C:\Users\User\splatnet2statink> python splatnet2statink.py -r
splatnet2statink v1.5.6
Blank cookie.
Attempting to generate new cookie...
PS C:\Users\User\splatnet2statink> python splatnet2statink.py -r
splatnet2statink v1.5.6
Blank cookie.
Attempting to generate new cookie...
PS C:\Users\User\splatnet2statink> python splatnet2statink.py -r
splatnet2statink v1.5.6
Blank cookie.
Attempting to generate new cookie...
PS C:\Users\User\splatnet2statink> python splatnet2statink.py -r
splatnet2statink v1.5.6
Blank cookie.
Attempting to generate new cookie...
PS C:\Users\User\splatnet2statink>`

And so on...

Then I tried the manual method with mitmproxy, but that also doesn't appear to be working anymore. Don't know if it's an API update again or if the steps are just outdated. At step 6, where I would go to the Nintendo Switch App, it instantly gives me an error code, and I can't even go to the Splatoon 2 section within it. I double checked if I did all steps before it correctly, and I did, even shows some network flow in the mitm command line, just nothing from the Nintendo Switch app.

The Error Code in the app is: 2817-0599.

Now I find no other way to generate cookies and I don't know if the update broke it for me or what this causes

**Comment by frozenpandaman** [comment]
Likely the same as #108, so closing for now. Please don't have your script/setup constantly retry upon failure to generate a cookie, though, as this puts strain on my personal web server.

For why mitmproxy may not be working, see the [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) page, specifically the note at the very top – you need to use iOS or a specific version of Android.
