### ISSUE TITLE
S2S unable to change the script for what S2S uploads to stat.ink

### ISSUE THREAD

**Issue by UmbreonRyguy** [frozenpandaman/splatnet2statink#111]
when I run S2S it automatically asks to enter a number 0-50 of the battles you want to upload but there is no way to change it to the other options like /path/to/splatnet2statink.exe -M 900 which puts it in monitoring mode or /path/to/splatnet2statink.exe --salmon -r which updates all salmon run matches. how can I fix/change it?

**Comment by ofiala-a51** [comment]
You have to run it with those options if you want that functionality. So instead of executing `splatnet2statink.py`, you have to execute `splatnet2statink -M 900` if you want to run it in monitoring mode and check each 900 seconds. Similarly for the other options.

**Comment by frozenpandaman** [comment]
I assume you're clicking on the pre-compiled executable version of s2s, not running the Python file from the command line. In this case, you'll need to open your terminal (Command Prompt/PowerShell) yourself first, drag in the .exe file (or manually type in the location of it), and then type the options after to run it.

**Comment by UmbreonRyguy** [comment]
> I assume you're clicking on the pre-compiled executable version of s2s, not running the Python file from the command line. In this case, you'll need to open your terminal (Command Prompt/PowerShell) yourself first, drag in the .exe file (or manually type in the location of it), and then type the options after to run it.

thx
