### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by lucyy-mc** [frozenpandaman/splatnet2statink#114]
Hiya!

No issue here, just thought I'd let you know I've published a package on the Arch User Repository [https://aur.archlinux.org/packages/splatnet2statink/](https://aur.archlinux.org/packages/splatnet2statink/). I'm still new to packaging and this seemed like a great first project.

**Comment by frozenpandaman** [comment]
Very cool! Thanks for letting me know! :D
