### ISSUE TITLE
Request to use your api in my application.

### ISSUE THREAD

**Issue by JoneWang** [frozenpandaman/splatnet2statink#117]
I have developed two applications:
- [Sp2BattleBot](https://github.com/JoneWang/sp2battlebot) - Get game data in telegram.
- [imink](https://github.com/JoneWang/imink) - View and record game data in iOS. (In development)

Would like to use your API when logging in. Hope you will agree.

I will do the following things:
1. I will ask @NexusMine for permission at the same time.
2. The code I will open source using GPLv3 license.
3. Completely free. No insider purchases or donations.
4. Declare to use your API and @NexusMine's API and thank splatnet2statink and ikaWdiget2 for help.
5. Provide iksm_session login scheme in future updates.

**Comment by frozenpandaman** [comment]
Hiya! Sorry, I was away from my computer for some time. I replied to briefly you on Twitter about this already, but yes, no problem! Sounds great. Please make sure to use properly-formatted, unique user agent string(s) so I know it's your app(s) making requests to the API. :)

Feel free to release imink on the Apple App Store, which you mentioned, as well! Thanks. :)

**Comment by JoneWang** [comment]
Thank you very much!

**Comment by JoneWang** [comment]
Hi. Thank you and @NexusMine for the api.

I have recently implemented the f generation. I will use imink api instead of s2s api and flapg api in the next version of imink.

During the promotion of imink users often got login errors due to the request limit of the s2s api. s2s api has a request limit of only two users per minute. During the promotion period we had 4-5 users per minute logging into imink, so using the s2s api was not the best solution for imink.

Thanks again for providing the api, I will keep the links to splatnet2statink and @NexusMine in the README of the project to show my appreciation.

**Comment by frozenpandaman** [comment]
@JoneWang Wow, that's a lot. I'm glad you were able to find an alternative solution. Thank you for the update and support!
