### ISSUE TITLE
Turf inked for ranked battles?

### ISSUE THREAD

**Issue by IceFlinger** [frozenpandaman/splatnet2statink#12]
Seems like your turf inked amount doesn't get sent to stat.ink when playing ranked battles.

**Comment by clovervidia** [comment]
I'm not sure if stat.ink shows turf coverage for ranked battles, but it would be a simple fix if it does.

**Comment by clovervidia** [comment]
That should do it.

**Comment by IceFlinger** [comment]
Thanks!
