### ISSUE TITLE
Could not decode binary that contained an image data

### ISSUE THREAD

**Issue by DaYu525** [frozenpandaman/splatnet2statink#120]
Battle uploaded to https://stat.ink/@20789647/spl2/3689791
Error uploading battle. Message from server:
{
    "error": {
        "image_result": [
            "Could not decode binary that contained an image data."
        ]
    }
}
Battle uploaded to https://stat.ink/@20789647/spl2/3689805

**Comment by DaYu525** [comment]
I checked the nintendo online app and stat.ink, that failed upload data have uploaded succeed in succedent upload action.

**Comment by frozenpandaman** [comment]
Sounds like stat.ink just messed up for a sec, I presume, but glad you got it worked out!
