### ISSUE TITLE
Not able to generate cookie: "Upgrade required"

### ISSUE THREAD

**Issue by theatredays** [frozenpandaman/splatnet2statink#124]
Hello! Was able to view Splatnet on the web a few days ago using this script to generate a cookie. Wasn't working for me today, so I tried to generate a new cookie but getting this error:

```
Attempting to generate new cookie...
Error from Nintendo (in Account/Login step):
{
  "status": 9427,
  "errorMessage": "Upgrade required.",
  "correlationId": "a6baabe6-fcda2862"
}
```

**Comment by frozenpandaman** [comment]
Sorry, I've been really busy – this will get fixed when #123 gets merged. I'll try to get around to it tonight.

**Comment by frozenpandaman** [comment]
@theatredays Fixed now!

**Comment by theatredays** [comment]
Works great now, much appreciated!! Thanks for creating this script! 😄
