### ISSUE TITLE
Stuck at "attempting to generate new cookie..."

### ISSUE THREAD

**Issue by luiscarlospando** [frozenpandaman/splatnet2statink#127]
Hi, I have never had any issues before, but today when trying to upload my battles using `python splatnet2statink.py -r` the app suddenly stops after getting the `Attempting to generate new cookie...` message.

Has anything changed from Nintendo's side?

Can you try uploading new battles?

Thanks.

**Comment by luiscarlospando** [comment]
Nevermind, I think the problem was on my end. I tried running it on another computer and it worked flawlessly.

Sorry for the bother!

**Comment by frozenpandaman** [comment]
Sorry I didn't have time to look at this yet, glad you got it figured out!
