### ISSUE TITLE
Automatically updating NSO app headers

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/splatnet2statink#129]
[via](https://github.com/frozenpandaman/splatnet2statink/commit/6f39882a07843f9c52be87059fda2b313e93ee9f#commitcomment-58531127) @tom-morita

> A_VERSION = "1.5.13"
> Error occurs for 2 days.
> ************************************************
> 
> Wrote session_token to config.txt.
> Attempting to generate new cookie...
> Error from Nintendo (in Account/Login step):
> {
>   "status": 9427,
>   "errorMessage": "Upgrade required.",
>   "correlationId": "3d7b138f-///snipped///"
> }

**Comment by niyari** [comment]
I noticed that there are several ways to do this.
https://github.com/niyari/splatnet2statink/commit/9dc7e042b3094d5e4bf5dc2bf3d32a7c8635c5a2

- Get from the Japanese support page. It's more maintained than other languages.
   https://www.nintendo.co.jp/support/app/nintendo_switch_online_app/index.html
- Get from the Google Play page, scrape string from the HTML.
   https://play.google.com/store/apps/details?id=com.nintendo.znca&hl=en
- Get from the iTunes (iOS) API. This is the cleanest way to get it, but it may cause version differences with Android.
   https://itunes.apple.com/lookup?id=1234806557&country=JP

**Comment by frozenpandaman** [comment]
@niyari Thank you!! I saw [your tweet](https://twitter.com/sou_niyari/status/1455268865290555396) about this too but didn't have a chance to reply yet. 😅

Thanks for looking into this and the different ways to accomplish it! All of those seem pretty decent and may all work in practice. Will give some more thoughts soon.

**Comment by frozenpandaman** [comment]
I'm going to play with this when the NSO app & store listing next updates – then will be able to have a real, live webpage to test it against and see what's best. :)
