### ISSUE TITLE
'ModuleNotFoundError' is not defined error

### ISSUE THREAD

**Issue by luiscarlospando** [frozenpandaman/splatnet2statink#131]
I don't know if it's just me or what but since I updated to the latest version I get the following error:

```
Traceback (most recent call last):
  File "splatnet2statink.py", line 22, in <module>
    except ModuleNotFoundError as e:
NameError: name 'ModuleNotFoundError' is not defined
```

Can you please help me?

**Comment by frozenpandaman** [comment]
@luiscarlospando What version of python are you using? You can run `python --version` to find out.

**Comment by luiscarlospando** [comment]
Currently I'm using `v2.7.17` on macOS.👀

**Comment by frozenpandaman** [comment]
Python 2 was deprecated on January 1, 2020. You'll want to use Python 3, which is the current, modern version. :) It's easy to get on macOS. From the readme:

> install [Homebrew](https://brew.sh/) and then run `brew install python`

Hope this helps!

**Comment by luiscarlospando** [comment]
Thanks for your help, gonna update right away!
