### ISSUE TITLE
splatnet2statink-v1.7.1-Windowsのsplatnet2statink.exeを実行すると，error: Too many requestsが発生する

### ISSUE THREAD

**Issue by Polyotu** [frozenpandaman/splatnet2statink#139]
2022/05/26から，以下のエラーが出て停止してしまいます．

```
D:\Users\username\Documents\splatmusicprj\splatnet2statink-v1.7.1-Windows>splatnet2statink.exe
splatnet2statink v1.7.1
Pulling data from online...
Blank cookie.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "Too many requests"
}
```

実行した後のconfig.txtは次のようになっていました(一部xに置換して伏せています)．
```
{
    "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "session_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "user_lang": "ja-JP"
}
```

過去のissueと比較して，#92, #91と近いのではないかと考えています．

v1.7.1のsplatnet2statink.pyを実行しても同様の状態になることを確認してから，
iksm.pyの331行目でapi_responseをprintさせると出力は次のようになっていました(一部xに置換して伏せています)．
```
Wrote session_token to config.txt.
Attempting to generate new cookie...
<Response [200]>
Error from Nintendo (in Account/Login step):
{
  "status": 9427,
  "errorMessage": "Upgrade required.",
  "correlationId": "xxxxxxxx-xxxxxxxx"
}
```

**Comment by guigas7** [comment]
same here
![image](https://user-images.githubusercontent.com/11247506/170595607-0f76ad69-69ba-49b1-b977-a6f51d0fad7b.png)

**Comment by frozenpandaman** [comment]
Thanks! So sorry – someone was spamming the server with an unrecognized user agent. They've been blocked. That takes care of the "Too many requests" issue…

Not sure about the "Upgrade required" thing, will look into it.

**Comment by frozenpandaman** [comment]
Seems Google changed up the app's [Play Store page design](https://play.google.com/store/apps/details?id=com.nintendo.znca&hl=en_US&gl=US) and there's no way (??) to extract version # from it anymore. So the app updated to 2.1.1 but the headers couldn't auto-update. I changed it to scrape the iOS App Store page instead.

Fixed in 809564e / v1.7.2.

ありがとうございます、 @Polyotuさん！直しました。😊

**Comment by Polyotu** [comment]
対応ありがとうございます！
