### ISSUE TITLE
v1.7.2に更新後 "splatnet2statink version update required"が発生する

### ISSUE THREAD

**Issue by TakuKatayama** [frozenpandaman/splatnet2statink#140]
以下のエラーが発生するようになりました。

splatnet2statink v1.7.2
Pulling data from online...
Blank cookie.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "splatnet2statink version update required"
}

**Comment by frozenpandaman** [comment]
すみませんです！！
直しました。今からOK。
