### ISSUE TITLE
9599 - Unexpected Error - On Login/Account step

### ISSUE THREAD

**Issue by Jetsurf** [frozenpandaman/splatnet2statink#143]
Hello again!

This is more of a heads up. My project was starting to pick up errors on game service token creation, so in the troubleshooting of that, I tested with this project again.

Seems something has changed in the call to https://api-lp1.znc.srv.nintendo.net/v3/Account/Login as it's now throwing the error in the title. -SNIP: See edit-

We're still digging into the issue for our project, and if we make any progress we can let you know!

EDIT: Seems Nintendo updated some of their endpoints according to iMink.

**Comment by samuelthomas2774** [comment]
Nintendo managed to break everything because they now seem to be validating the `timestamp` parameter. For iOS it should be the timestamp in seconds as splatnet2statink and as far as I know everyone else does, but for Android it should be in milliseconds. What I think has changed is that it now needs to exactly match the time on the device used to generate the `f` parameter (which itself hasn't changed), so imink/flapg need to be updated to get the timestamp from the Android device/emulator and return it in the response instead of accepting it in the request.

**Comment by Jetsurf** [comment]
That makes sense! Thanks for the update. I'm actually splitting my project into a python library similar to nxapi, so you'll see me in there shortly!

**Comment by Adrthegamedev** [comment]
Yeah, I've been noticing this as well since the latest update; hope it'll get fixed here!

**Comment by frozenpandaman** [comment]
Apologies for my late reply (start of the school semester!) – thanks for that info, @samuelthomas2774. :)

As of v1.8.0 (8cec959) splatnet2statink is now using the imink API (fyi, I'll be using this for [**`s3s`**](https://github.com/frozenpandaman/s3s) too), and to my knowledge it's yet to be updated in the way that will automatically fix this issue. @JoneWang has posted a temporary workaround at https://github.com/JoneWang/imink/wiki/imink-API-Documentation but I don't think it's worth changing our code & making another v1.8.1 update to patch this in, given it should be fixed the "proper" way pretty soon & the API functionality updated to take care of it.

**Comment by frozenpandaman** [comment]
Apologies for my late reply (start of the school semester!) – thanks for that info, @samuelthomas2774. :)

As of v1.8.0 (8cec959) splatnet2statink is now using @JoneWang's imink API (fyi, I'll be using this for [**`s3s`**](https://github.com/frozenpandaman/s3s) too), but it's yet to be updated in the "best" way to fix this issue (by actually returning the timestamp along with `f` tokens as needed). There's some more, updated information available at https://github.com/JoneWang/imink/wiki/imink-API-Documentation

I'm going to release s2s v1.8.1 in just a minute with a temporary/janky fix for this, but there should be another minor increment shortly (as soon as the imink API is able to be updated) with the "proper" way to deal with what's causing the error.

**Comment by frozenpandaman** [comment]
FYI, in case it helps in the future, all error codes are listed here: https://github.com/samuelthomas2774/nxapi/blob/main/src/api/coral-types.ts#L13-L54
