### ISSUE TITLE
What is the license for this app?

### ISSUE THREAD

**Issue by Dogey11** [frozenpandaman/splatnet2statink#146]
Hi! Am I allowed to borrow some of the code for a project? Specifically the Nintendo login part.

**Comment by frozenpandaman** [comment]
Hi! The license is specified at the end of the readme (albeit not in a standalone file so it's a bit harder to spot). It's GPLv3, i.e. please give attribution or a link back to this project, and release your code under the same terms, but feel free to use the code/logic as needed. :)

Thanks!
