### ISSUE TITLE
how to change scope in authorize url

### ISSUE THREAD

**Issue by Asteroidxx** [frozenpandaman/splatnet2statink#147]
when I want to change scope for get more user inforamtion, I can't open the url.

**Comment by frozenpandaman** [comment]
Hi, sorry, what do you mean? I need more information as to what your issue is or what you're wanting to do.

**Comment by Asteroidxx** [comment]
Thank you,I have solved the problem.

**Comment by Asteroidxx** [comment]
Thank you,I have solved the problem.
Now I had get 'access_token' and 'id_token' from request "https://accounts.nintendo.com/connect/1.0.0/api/token"，I use them to request "mypage-api.entry.nintendo.co.jp/api/v1/users/me/play_histories" for get user's history game, but I get a response value of "The Token could not be parsed".

**Comment by frozenpandaman** [comment]
Sorry, I don't think this is s2s-related. I can point you to further resources if you're interested in other NSO app functions and endpoints.

**Comment by Asteroidxx** [comment]
Thank you! I want to know about them.

**Comment by frozenpandaman** [comment]
@Asteroidxx Checking out these repos & discussions should help:

https://github.com/samuelthomas2774/nxapi
https://github.com/samuelthomas2774/nxapi/discussions/10
https://github.com/ZekeSnider/NintendoSwitchRESTAPI

**Comment by Asteroidxx** [comment]
Thanks！ It will help me a lot.
