### ISSUE TITLE
about the client id

### ISSUE THREAD

**Issue by vincenzoiovino** [frozenpandaman/splatnet2statink#149]
Hello, everyone
I would like to figure out the role of the "client id".
In other REST interface (Google, Facebook,...) this is something you create in your development account. So the question is:
is this client id that appears in the repo created by someone and we are all using it or what is it?
In this or another repo (?) I found out that it is mentioned that it is related to Splatoon2 game but I think it is a typo because the id of the game is different and appears in a different context.

Thank you in advance
Kind regards

**Comment by frozenpandaman** [comment]
Discussion of this is more suited to https://github.com/samuelthomas2774/nxapi/issues/12
