### ISSUE TITLE
The provided grant is invalid / The URL has expired

### ISSUE THREAD

**Issue by tugofwardolphin52** [frozenpandaman/splatnet2statink#151]
OS: Windows 10

Hello, I'm not tech savvy or understand programming but I'm starting to have an issue with splatnet2statink and hope someone could help me with it. I use both splatnet2statink and s3s and haven't had issues with them until after March 7, 2024 when I downloaded and set up Nxapi to display my Switch gameplay with Discord's rich presence. S3s was able to work again immediately on that day after going through its instructions, but I'm unable to figure out how to solve splatnet2statink's issues today when I ran it for the first time since installing and running Nxapi.

Upon running splatnat2statink, I was greeted with this message:
```
splatnet2statink v1.8.4
The stored cookie has expired.
Attempting to generate new cookie...
Not a valid authorization request. Please delete config.txt and try again.
Error from Nintendo (in api/token step):
{
  "error_description": "The provided grant is invalid",
  "error": "invalid_grant"
}
```
I deleted config.txt and reran splatnet2statink, already knowing what to expect since it was the same procedure as s3s.
```
C:\Users\[my username]\splatnet2statink>splatnet2statink.py -M -r
splatnet2statink v1.8.4
Generating new config file.
stat.ink API key: [I pasted my API key here as requested]
Default locale is en-US. Press Enter to accept, or enter your own (see readme for list).

Blank cookie.
session_token is blank. Please log in to your Nintendo Account to obtain your session_token.

Make sure you have fully read the "Cookie generation" section of the readme before proceeding. To manually input a cookie instead, enter "skip" at the prompt below.

Navigate to this URL in your browser:
https://accounts.nintendo.com/connect/1.0.0/authorize?state=[blanked out for privacy]
Log in, right click the "Select this account" button, copy the link address, and paste it below:
[I pasted the address as requested]
```
But when I hit enter, I got the message "The URL has expired. Please log out and back into your Nintendo Account and try again.", which never happened with s3s when I had to do this with it. I logged out and back in, then tried to rerun it all over again only to get the same error about the URL expiring even though it was less than a minute when it was generated.

I won't be able to manually obtain the cookie with the NSO app on my Android because the app has recently been rendered incompatible, which is one of the reasons why I'm now using Nxapi.

**Comment by frozenpandaman** [comment]
Oh, thanks for the reminder! This is the same error as frozenpandaman/s3s#174, I just only fixed s3s and forgot about splatnet2statink. Should be working very shortly. :)
