### ISSUE TITLE
Failure to handle (null rank) in private match

### ISSUE THREAD

**Issue by emaame** [frozenpandaman/splatnet2statink#22]
Since I have never played "ガチアサリ" , my udemae is null rank.
Then I played "ガチアサリ" in Private match, splatnet2statink.py failed to handle it.

```
Traceback (most recent call last):
  File "./splatnet2statink.py", line 894, in <module>
    monitor_battles(is_s, is_t, is_r, m_value, debug)
  File "./splatnet2statink.py", line 286, in monitor_battles
    post_battle(0, [result], s_flag, t_flag, secs, False, debug, True)
  File "./splatnet2statink.py", line 723, in post_battle
    rank_before = rank_before.lower()
```

I think lower should go to try clauses, not else.
It seems that getting `results[i]["player_result"]["player"]["udemae"]` doesn't raise Exception.

```
        try:
                rank_after = results[i]["udemae"]["name"].lower # It could be non null value if it is the first game of that rule
                rank_before = results[i]["player_result"]["player"]["udemae"]["name"].lower
                rank_exp = results[i]["player_result"]["player"]["udemae"]["s_plus_number"]
                rank_exp_after = results[i]["udemae"]["s_plus_number"]
        except: # based on in-game, not app scoreboard, which displays --- (null rank) as separate than C-
                rank_exp = None # e.g. private battle where a player has never played ranked before
                rank_exp_after = None
                rank_after = None
                rank_before = None
```

It works in my records.

thanks.

**Comment by clovervidia** [comment]
Do you happen to have the JSON file for that battle from SplatNet 2? I'd like to run a few tests, as this would be the first time they've added a new game mode so it's possible some people won't have a rank for it at all when played in a private battle. If you don't know how to get the JSON, I can walk you through the process if you have your iksm_session cookie from the config.txt file.

**Comment by frozenpandaman** [comment]
Ughhhhh... have tried to fix this a number of times now and seems the logic is still a bit off. Sorry @emaame. That makes sense, it can't `.lower()` the null `rank_before`. Setting `rank_after` first is smart.

Here's one of the iterations of what we tried before that also didn't completely work:
https://github.com/frozenpandaman/splatnet2statink/blob/2508c197d2e7c63e9f258244b0e303d5a72fd684/splatnet2statink.py#L712-L730

I'll change the code based on your suggestion, since you said that solution works for you.

**Comment by frozenpandaman** [comment]
Let me know if 80cd153 (v0.2.9) fixes it!

**Comment by emaame** [comment]
Thank you!
I'll try to get raw JSON.
And I check a new one.

**Comment by emaame** [comment]
1. `80cd153`
`80cd153` works correctly!!
Thank you!!

2. JSONs
[null_rank_jsons_20171216.zip](https://github.com/frozenpandaman/splatnet2statink/files/1564498/null_rank_jsons_20171216.zip)

I got raw JSONs of private matches with proxy.
It still be not anonymized.

**Comment by frozenpandaman** [comment]
Yay, awesome! 😄

**Comment by clovervidia** [comment]
I appreciate the JSONs. If you want, you can remove the file from the comment to keep them out of the wrong hands.  
And as a side note, I recently worked on anonymizing the payload, so if you want to anonymize it, you just need to go through the two arrays with players (`my_team_members` and `other_team_members`) and remove/replace the `nickname` and `principal_id` for each player as those are what appear to me as the identifiable information.

**Comment by frozenpandaman** [comment]
`principal_id` is unique for every user but there's no way of finding out who it is just from that (only that, between multiple battles, a player may be the same person.) It's not exactly identifiable information, and leaving it in would make the data de-identifiable, (compared to anonymized). We've set the script up to remove both, though,

**Comment by emaame** [comment]
Nice.  I'm so glad to your rapidly responses.
I just removed JSONs.
