### ISSUE TITLE
"pip install pillow" is required even without "-s" option

### ISSUE THREAD

**Issue by Tiryoh** [frozenpandaman/splatnet2statink#23]
I got an error like this on version https://github.com/frozenpandaman/splatnet2statink/commit/abc070e4e37ed2cbff11f1d70db924c120e7960d.
```
$ ./splatnet2statink.py -r -M 1200
Traceback (most recent call last):
  File "./splatnet2statink.py", line 11, in <module>
    from PIL import Image, ImageDraw
ImportError: No module named PIL
```

`pip install pillow` solved this problem, so I assume that `pip install pillow` is required.

**Comment by frozenpandaman** [comment]
Oh lol I'm dumb. Thanks @Tiryoh. :)

PIL/Pillow is only used with the `-s` flag so as of dffc9a0 I've conditionally imported it. Now this probably isn't good Python style (but hey, it is allowed) but I'd really like to not force users to install it if they don't need it… and it's only needed in a case that I don't think most people use. (2 dependencies to install by hand is OK, but 3 is getting to the point where it'd probably be better to have a requirements.txt…)

**Comment by Tiryoh** [comment]
@frozenpandaman 
I got it.  Thanks for your support!
