### ISSUE TITLE
Tabs => Spaces?

### ISSUE THREAD

**Issue by martinemde** [frozenpandaman/splatnet2statink#26]
My editor is rather annoying about this [W191 Indentation contais tabs](https://docs.quantifiedcode.com/python-anti-patterns/correctness/indentation_contains_tabs.html), highlighting every line and tab in the whole file and refusing to indent with tabs as I work.

I realize tab/space is practically a religious war, and I'm suggesting only at *gives-a-shit-level* of 1 out of 10.

I can shut off vim's syntax checking and fix my tab highlighting, but if you're open to it, it's something that a quick regex would fix.

Please close immediately if it's not worth doing.

**Comment by frozenpandaman** [comment]
I know @clovervidia and I both prefer using tabs. And while I do love style guidelines, I love my tab key more. （●＾o＾●）

So I think we'll stick with tabs for now, if that's OK! 😆

**Comment by martinemde** [comment]
No problem, I'll set up my editor to make it less annoying :+1:

**Comment by frozenpandaman** [comment]
Glad you'll be able to find a solution! :)
