### ISSUE TITLE
Uploading previously un-uploaded battles sometimes uploads very old battles

### ISSUE THREAD

**Issue by martinemde** [frozenpandaman/splatnet2statink#30]
I have now seen this problem.

When I ran this script with only -r, it started uploading battles that were beyond the last 50 according to Stat.ink at the time. It seems like I had some duplicates that leaked into stat.ink at first, which broke the 50 offset from stat.ink, causing the oldest battles to be duplicated at the top.

I'm not sure what started this offset initially. Something caused a duplicate battle. Since the maximum from Stat.ink is 50 battles, we can never recover once there are recent duplicates.

This could also be solvable from Stat.ink, which could enforce uniqueness on player and battle ID. Has this been discussed? CC @fetus-hina 

Edit: I updated this a bunch given new info I found. It seems clear that SplatNet is *not* sending back more than 50, but that Stat.ink ends up with a bad offset that can't easily be reconciled until that duplicate battles are deleted.

**Comment by clovervidia** [comment]
What do you mean SplatNet returns battles that are more than 50 battles old? Are you saying sometimes it returns more than 50 battles?

**Comment by martinemde** [comment]
@clovervidia I updated my comment. That's what it looked like at first because Stat.ink showed the battles being duplicated as my 62-58th battles. However, the offset on Stat.ink seems to have been broken by other duplicates.

It's still occurring actually even after I deleted the duplicates. I'm still investigating why.

**Comment by clovervidia** [comment]
I think I see what you're saying now about the offset. I usually upload my latest battle multiple times if I'm testing something, which could cause stat.ink's list of battle numbers to push old battles off the end which are still in SplatNet.

Do you think increasing the number of battles stat.ink returns to something like 75 or 100 could solve this? It would add some overlap to cover for duplicate or missing battles. I also wonder if spectator mode games factor into this as that battle number would be skipped entirely.

**Comment by martinemde** [comment]
It seems like that would fix it, but we'd need @fetus-hina to update stat.ink to allow it. [API Docs](https://github.com/fetus-hina/stat.ink/blob/master/doc/api-2/get-battle.md)

**Comment by martinemde** [comment]
I think I caused my original problem by running -M locally, while having my script overlap. Since -M doesn't repeatedly check Stat.ink, any battles that are uploaded separately added after the monitoring sessions started would be duplicated.

**Comment by clovervidia** [comment]
When I ran into the issue, I ran it locally with -M and -r to pick up a battle that finished before I started the script. Checking stat.ink after each battle might be a solution, but it might also be taxing on their servers. Duplicate battles do seem to be a theme here.

I can talk to them about increasing the number of battles that get returned to see if it's reasonable, or if 50 itself reaches some resource limit.

**Comment by fetus-hina** [comment]
As a developer of stat.ink:

- Client gets more data (e.g. 75-100 SplatNet's `number`s)
    - I can update it (up to 100 or 200 battles) and this way is easy.

- Statink skips register an "old" battle
    - Although it is technically possible, I don't think I want to do it aggressively at this time.

- Statink supports to check by a client
  - I can implement it (it may be enhancement of exist method). But I think it may cause a race condition. (Client A checks -> Client B checks -> Client A posts -> Client B posts -> Duplicated!)
  - Do I have to really think about double monitoring???

https://github.com/fetus-hina/stat.ink/issues/322, the issue mentioned to this issue I created, is just a note for me.

**Comment by frozenpandaman** [comment]
This was happening for me without duplicates on stat.ink. (Unlike @clovervidia I have no duplicates on my stat.ink.)

@martinemde, what do you mean by "offset"?

Anyway, this doesn't seem to be an issue for me anymore/at the moment (unless I were to maybe fool around with deleting battles on stat.ink to try and reproduce it), but I think this is the reason it happened for me before:

1. Uploaded battles in monitoring mode or manually (say, 4 battles)
2. Realized there was a 5th battle that was not uploaded.
3. I wanted my battles to be displayed in order on my stat.ink userpage, so I manually deleted the 4 just-uploaded battles
4. Re-uploadd all 5 battles

In the case where one uses `-r` to re-upload these battles (step four), I *think* the deleted battles were causing an issue (???) and thus this was leading to battles being uploaded that already were listed/had been uploaded previously.

**Comment by martinemde** [comment]
Would it make sense for stat.ink to support a `unique` option that would reject uploads for battles that already exist? Then nothing changes for anyone that doesn't choose to change it and we avoid the race condition.

Receiving the last 100 battle numbers is also simple and makes the problem much less likely.

I really don't think this is a common issue. It also cannot be completely new since the behavior of `-r` could have always done this if Stat.ink did not return a battle number that was returned by SplatNet.

**Comment by clovervidia** [comment]
I believe that's already possible if we calculate and set a UUID. Our script doesn't do this currently, but if it were set, based on the API docs for stat.ink, the server would reject later battles that have the same UUID as a previously uploaded one. It does mention a time period that the server checks for duplicate UUIDs, and I'm not sure how long that is, as it could be a few minutes, a few hours, or maybe a day. And using it would mean we could choose to not send it during testing if duplicate battles are expected.

I'm not sure how many users actively use `-r`, so it's possible this issue has been around for a while. I would imagine most people just use start it up with monitoring when they start playing and stop it afterwards, or upload their latest 50 manually.

**Comment by fetus-hina** [comment]
Stat.ink's `uuid` field currently checks duplicates for 24 hours (86400 seconds) at this time. (If client provide it)
https://github.com/fetus-hina/stat.ink/blob/611f648da92c697a1bd2ee44bb3a9933585e27ac/models/api/v2/PostBattleForm.php#L45


BTW, I use `-r` flag without `-M` flag.
I was set a cron task this script to my Linux VPS server: (and my account have no duplicated battles)
```bash
#!/bin/bash
set -eu
pushd /home/splatnet2statink/splatnet2statink
    /usr/bin/git pull origin master
    /bin/yes | /usr/bin/python2 splatnet2statink.py -r
popd
```

**Comment by clovervidia** [comment]
24 hours sounds like a reasonable time frame to catch duplicates in case a user agent uploads the same battle multiple times due to a network error or some other condition preventing it from uploading. However, since this issue seems to occur when the agent is run multiple days apart, I don't think it will help here.

I think I see what @martinemde is suggesting now. Setting a flag in the payload to tell stat.ink to reject the battle if that SplatNet battle number already exists on that user's account. We were planning to use UUIDs in our script for this purpose, but we didn't want to put unnecessary load on the stat.ink servers by sending entire payloads that could get rejected, which is why we requested the ability to get a user's SplatNet battle numbers so we could check them locally before sending anything. It sounds to me like increasing the number of SplatNet battle numbers the endpoint returns could solve this issue with relative ease compared to the other solutions. What do you think, @fetus-hina ?

I don't think @frozenpandaman or I initially imagined running the script anywhere other than on a local computer, but I'm glad there are new ways to use it being found. That extension to `-r` of yours is coming in handy already, huh @martinemde ? Duplicate battles shouldn't be uploaded if the script is used normally and not being used to test something, so this probably isn't too widespread.

**Comment by fetus-hina** [comment]
As for a [`GET /api/v2/(?:user-)?battle` request with `only=splatnet_number`](https://github.com/frozenpandaman/splatnet2statink/blob/59ab88049afe3e5b6e74bb55eb378899881a94dc/splatnet2statink.py#L287), it sounds good to me.
It works well in case of users switch their client like "SquidTracks to splatnet2statink", the uuid field is not compatible because it generates by client.

**Comment by fetus-hina** [comment]
I have updated API spec and its implementation. Now clients can get `splatnet_number`s up to 1000.
[Example: Get 100 battles](https://stat.ink/api/v2/battle?screen_name=fetus_hina&count=100&only=splatnet_number)

Depending on the outcome of this discussion, I'll implement more things if needed.

**Comment by frozenpandaman** [comment]
Awesome, thank you @fetus-hina!

**Comment by frozenpandaman** [comment]
Thanks @fetus-hina! Good note about the UUID field.

We'll change the `count` URL parameter to 100 for now, then, at the line you linked to. 🙂

Like your example, the using the [`/v2/battle` URL](https://stat.ink/api/v2/battle?screen_name=frozenpandaman&count=100&only=splatnet_number) will return 100 battles. But when I try with the [`/v2/user-battle` version](https://stat.ink/api/v2/user-battle?only=splatnet_number&count=100) I still get this message:
```
{
    "count": [
        "Count must be no greater than 50."
    ]
}
```

**Comment by fetus-hina** [comment]
Oh, sorry. Fix it soon.

**Comment by frozenpandaman** [comment]
No rush. Thanks! 😊

**Comment by fetus-hina** [comment]
Fixed it

**Comment by frozenpandaman** [comment]
Looks good! I've staged the changes to update `50` to `100` in the URL, which should realistically cover our bases based on previous discussion. I want to do a final check with @clovervidia before I push to confirm that this sounds good, or if anyone has other input/feedback as well.

**Comment by martinemde** [comment]
This seems like an easy fix and it’ll solve the problems I’m aware of. Thanks everyone.

As for the UUID, it makes a lot of sense to send that just to help with network issues. It’s awesome that your API supports this @fetus-hina. I don’t often see idempotency keys in APIs and I wish more APIs would do this.

It looks like UUIDv3 could support generating the same uuid given the same input. We could pick something consistent (like battle ID + user ID) and generate a UUID that would prevent clients from accidentally duplicating if they crash or exit in the middle of an upload. I think this is still a minor issue but I love that it’s supported by Stat.ink.

Thanks for this solution everyone! A few weeks ago I didn’t even think tracking my stats was possible without manual data entry, so this is all awesome.

**Comment by clovervidia** [comment]
I was thinking of using some combination of the battle ID, time the battle started, and maybe turf inked, since you can reliably get these three from any mode. I don't think it's necessary since we check the battle IDs on stat.ink against the 50 that SplatNet provides us to avoid duplicates, but I also don't see the harm in implementing it as a precaution should a similar issue come up again. 

At any rate, we should keep an eye on this for a while to make sure it doesn't happen again, and that it wasn't actually caused by some other factor.

**Comment by frozenpandaman** [comment]
Info for consideration

- UUIDs are unique per user (i.e. not globally unique)
- @fetus-hina suggests UUID = principal_id + battle number
  - if user loses Switch or save file, can keep uploading using same stat.ink account

**Comment by fetus-hina** [comment]
I suggest a bit more:

- Use UUID v5 (SHA-1 based UUID) with namespace `73cf052a-fd0b-11e7-a5ee-001b21a098c2`
  - I generated this NS UUID now and defined it as "SplatNet 2 based record."
- The UUID generated from `principal_id` and `battle_number`.
  - The format is `battle_number@principal_id`, e.g. `42@abc123`
    - We'll get a UUID "`666cdcb7-aad2-5bc6-bb02-940d2c2f8301`" in this case.

If we define the API specification as above, we will be able to use the same UUID across applications.

**Comment by frozenpandaman** [comment]
Cool, thanks for expanding on that. I was talking with @clovervidia earlier about generating a UUID based on those two values – he mentioned that hashing seemed unnecessary to him, but we didn't come to any decision yet. I'm not super well-versed in this area either – what benefit would doing it the way you suggested provide? Just ensures true uniqueness based on those two values? And is that namespace (`73cf052a-fd0b-11e7-a5ee-001b21a098c2`) randomly generated? Just curious. 😊

This is how we'd do that in Python (for reference):
```
import uuid
namespace = uuid.UUID('{73cf052a-fd0b-11e7-a5ee-001b21a098c2}')
name = str(bn) + "@" + str(principal_id)
uuid.uuid5(namespace, name)
```

**Comment by fetus-hina** [comment]
> what benefit would doing it the way you suggested provide?

1. Stat.ink accept any string as `uuid`, but it **always** stores as well-formed UUID.
    - If given UUID is not valid, stat.ink will [convert it to UUID](https://github.com/fetus-hina/stat.ink/blob/7b3242cf767f9929d7e1eaa7b1abdea87359ce76/models/Battle2.php#L491-L504). Because the column defined as [`uuid` data type](https://www.postgresql.org/docs/10/static/datatype-uuid.html) in our DB.
        - If not given the `uuid`, generate v4 (random) UUID.
        - If given the `uuid` and well-formed, store it as is.
        - Otherwise, convert it to v5 UUID (with NS `15de9082-1c7b-11e7-8f94-001b21a098c2` (`CLIENT_UUID_NAMESPACE`) that defined as "converted UUID")
    - In other words, it is always hashed once or more.
2. Namespacing.
    - Stat.ink's `CLIENT_UUID_NAMESPACE` (above) just means "converted from string," this nearly equals "store it as is."
        - If your client (splatnet2statink) sends it `battle_number@principal_id` and other client (typically standalone, like IkaRec) sends like `sequencial_id@device_id_or_install_id`, they may collision.
        - It won't happen if you use a namespace.
            - Note: Hash values may conflict. But that's a pretty low probability. UUID v3/v4/v5 has `5.3×10^36` (= `2^122`) space. 
3. Stronger hash method
    - I suggested v5 (sha1) UUID, not v3 (md5). MD5 is dead. SHA-1 is stronger than MD5 but it is also dying. SHA-2 or SHA-3 based UUID is not defined.

> is that namespace (73cf052a-fd0b-11e7-a5ee-001b21a098c2) randomly generated?

The namespace `73cf052a-fd0b-11e7-a5ee-001b21a098c2` was generated in my physical linux box.
It is a version 1 UUID and contains "generated time" and "mac address (`00:1b:21:a0:98:c2`)" (Read RFC 4122, if you are interested).
It is a really unique ID. It doesn't (and won't) collision with any other UUIDs.

**Comment by frozenpandaman** [comment]
This completely makes sense. Thank you for taking the time to explain! Cool method...

I'm definitely in favor of doing it this way, then.

**Comment by frozenpandaman** [comment]
Implemented UUIDs and increased number of recent battles checked to 100 in 0a962a0.
