### ISSUE TITLE
Python 2/3 compatibility

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/splatnet2statink#38]
(See #28, #29 for some previous discussion.)

Let's work to support Python 3.x too, while not leaving 2.7.x users behind. This is important as Python 2.7 comes preinstalled on macOS and we want to make it easy for these users to run the script, even if they don't feel comfortable upgrading or working on the command line.

I've created the [`python3`](/frozenpandaman/splatnet2statink/tree/python3) branch. The conversion was done via [`futurize`](http://python-future.org/futurize.html) – which helps make projects support both Python 2 and 3 concurrently – with manual review + touchups afterward. I've done some testing and everything still seems to work (e.g. no random syntax errors). 95% of the changes were just changing `raw_input()` to `input()`, `xrange()` to `range()`, and making `print()` a function rather than a statement, i.e. adding parens…

This adds a single dependency which can be installed via `pip install future`. Note the updated README (particularly steps 1–2 of the Setup section) as well. The diff isn't that big, so check it out here: https://github.com/frozenpandaman/splatnet2statink/compare/master...python3

@clovervidia (or others who watch this repo 👀), thoughts or suggestions or fixes before merging this into `master`?

**Comment by martinemde** [comment]
Seems to work so far. I'll update if I see any problems. I'm going to run one of my instances with 2.7 and one with 3.6 with the same code.

**Comment by martinemde** [comment]
Working fine on python3. Haven’t been able to test 2.7 fully yet but seems fine.

**Comment by Lnk2past** [comment]
Is it worth using [six](https://pythonhosted.org/six/) to handle this? It is a pretty great module.

**Comment by martinemde** [comment]
FYI, I've switched to running on Python3 using your branch. Not testing python2 along side anymore. I didn't see any problem but it didn't get used much either since my wife hasn't played as much this week.

**Comment by frozenpandaman** [comment]
>Is it worth using six to handle this? It is a pretty great module.

Seems pretty similar to futirize. Or is there a difference you'd like to highlight?

Seems future/futurize is heavily preferred; here's one source about that: https://stackoverflow.com/questions/42110826/writing-cross-compatible-python-2-3-difference-between-future-six-and-fut

>I've switched to running on Python3 using your branch.

Same here, but also didn't run into any problems when running via Python 2.7 before making the branch. I was traveling this week at a conference and just got home. I'll merge this tonight or soon.

**Comment by Lnk2past** [comment]
Nah, no reason to pick up six then. I'll have to look into futurize for my own projects.

**Comment by frozenpandaman** [comment]
@martinemde @Lnk2past Would you say this merits a bump to ver. 0.3.0? Or should we just do the same version bump as usual weapon stage updates (e.g. 0.2.35 → 0.2.36)? Not even sure if it matters a whole ton but just trying to get some community opinion here and thought you two may have some thoughts. 😊

**Comment by martinemde** [comment]
SemVer would probably encourage 0.3.0. It’s a new feature that is backwards compatible. The point would be to say “you need version 0.3.0 or greater to run on python3” instead of “0.2.36 or heigher”.

**Comment by Lnk2past** [comment]
I agree, bumping to 0.3.0 seems appropriate.

**Comment by frozenpandaman** [comment]
>SemVer

SemVer is OK – but now let me introduce you to TenVer: http://tenver.drone-ver.org/

>The point would be to say “you need version 0.3.0 or greater to run on python3”

>I agree, bumping to 0.3.0 seems appropriate.

Thanks! I know @clovervidia was asking me for some justification as to what about this would merit calling it 0.3.0; this explanation makes a lot of sense to me, and that's what I was leaning toward as well too.
