### ISSUE TITLE
Can't seem to get iksm_session token from SplatNet 2

### ISSUE THREAD

**Issue by KunoichiZ** [frozenpandaman/splatnet2statink#39]
Hi, I'm trying to following the instructions [here](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) for obtaining my iksm_token and after entering my computer's IPv4 and the port as mentioned in Step 4, upon going to Step 5, my phone (iPhone SE, iOS 10.3.2) doesn't load http://mitm.it nor does it load the SplatNet 2 app. Safari tells me "Safari could not open the page because the server stopped responding" or that it's not running through the proxy and SplatNet 2 gives me a connection error, error code 2816-0599, "Internet connection is unstable". Am I missing an obvious step? Please and thank you for your help!

EDIT: I've fixed the Safari issue (I didn't have mitmweb running whoops) but SplatNet 2 either continues to give me the connection error or doesn't load anything after I click on Splatoon 2. Basically I can't get the little window to pop up that contains the iksm_session token.

**Comment by Lnk2past** [comment]
Hey @KunoichiZ,

Double check that you are using the _right_ IPv4_. Depending on you hardware and what other pieces of software that are installed, you may have multiple IPv4 entries. I had a similar issue because I was giving it the wrong IPv4 due to a Docker installation that setup its own IPv4 interface (and I just wasn't paying attention to it).

Not sure if that helps, but it is what worked for me.

**Comment by martinemde** [comment]
I had trouble with some of the instructions. They didn’t properly instruct setting the cert as a root certificate. Make sure you go into the profiles and trust as root. This caused most of my problems.

**Comment by KunoichiZ** [comment]
@Lnk2past I only have 1 IPv4 address listed. 
@martinemde How do I trust the cert as root?

**Comment by Lnk2past** [comment]
It wasn't anywhere in the mitmproxy tab that opened? Once you navigate to the Nintendo app and go tot he Splatoon 2 service, it should intercept the traffic. If you got this far the directions are pretty accurate (or at least they were for me). Maybe try navigating to some of the others that look similar?

**Comment by martinemde** [comment]
On iPhone, Settings > General > Profiles > mitmproxy

**Comment by martinemde** [comment]
I notice the step you're having trouble with might be earlier. If you were not able to reach http://mitm.it then you won't have the certificate yet.

Were you able to set the proxy up on your wifi network? Is this your own home network? Did you disable firewalls on your computer?

**Comment by KunoichiZ** [comment]
I managed to get it set up, but in the Request tab, where Cookie was, it didn't show "iksm_session: xxxxx". It showed some "GA" thing. I'll try again to see if it gives me anything different.

**Comment by martinemde** [comment]
I keep missing your edits. Sorry.

It looks like you're almost there. I deleted my previous comment since it made no sense now.

There were multiple listed on mine and the iksm_session is further in there. If you look for the string `iksm` it will be in there somewhere. Then just take the key. Mine looks like this: "9ca2bd76a23879ca2bd76a23879ca2bd76a7" (this is a fake one, but it's a hex string like this).

**Comment by frozenpandaman** [comment]
Sorry for not responding more quickly; I'm at a conference this week and only on mobile. If you're able to view entries on the mitmweb page that opens in your browser, mitmproxy is working.

If the cookie isn't listed under the `https://app.splatoon2.nintendo.net/?lang=en-US` entry, try looking at the one for `https://app.splatoon2.nintendo.net/api/data/stages`, or one of the other entries for that domain. There should be an entry of the format containing the text `iksm_session=`.

**Comment by frozenpandaman** [comment]
>I had trouble with some of the instructions. I had trouble with some of the instructions. They didn’t properly instruct setting the cert as a root certificate.

Also, please feel free to suggest any improvements to the readme or mitmproxy instructions wiki page, if they're off for you or missing any steps (different devices work differently, etc)... The instructions I wrote worked for me (i.e. I think I was prompted to enable it as root by default? or not at all and it still worked?) but I'll try reinstalling from scratch when I get home to make sure they're still up-to date for my own device, too.

**Comment by clovervidia** [comment]
@martinemde Is trusting a certificate as root a step required for iOS? I don't recall having to do that on Android, but the guide can certainly be updated if you have the steps you took to get the certificate to work for you.

**Comment by Tiryoh** [comment]
@clovervidia I tried on my iPhone SE(iOS 11.2.5), and it was necessary to trust certificate as root.

![img_2298](https://user-images.githubusercontent.com/3256629/37690939-ab9fa3cc-2cf1-11e8-9a58-751db37cfe0c.PNG)

**Comment by clovervidia** [comment]
Thanks for the detailed instructions. I'll add that and a link to the mitmproxy certificate installation docs (https://docs.mitmproxy.org/stable/concepts-certificates/) to the guide. Did you have to do anything else aside from setting up the certificate with full trust?

**Comment by martinemde** [comment]
Oops, I directed to the wrong menu in settings. @Tiryoh has the correct location.

**Comment by KunoichiZ** [comment]
@martinemde @frozenpandaman @Lnk2past Thank you for your help! The cookie in ``https://app.splatoon2.nintendo.net/?lang=en-US`` finally showed the proper iksm_session token.
