### ISSUE TITLE
KeyError: 'rank'

### ISSUE THREAD

**Issue by pixelyunicorn** [frozenpandaman/splatnet2statink#49]
After updating to v1.1.0, I ran into this error running splatnet2statink:

![image](https://user-images.githubusercontent.com/607807/39411288-2582f73c-4bd5-11e8-9e03-9d94f442e918.png)

I haven't had a chance to debug this, but I think this may be related to Rank X. (I am currently not Rank X in any mode.)

I am running Python 2.7.14 on a mostly vanilla install of Ubuntu 16.04.1 LTS (via SSH), if that helps.

**Comment by clovervidia** [comment]
I've also encountered this issue. I believe it's due to Turf War and League battles not including that field. Would you mind testing the "fix-worldwide-rank-not-existing-in-tw" branch and seeing if that fixes the issue?

**Comment by pixelyunicorn** [comment]
Nope, different error: 

![image](https://user-images.githubusercontent.com/607807/39411393-51e7cfee-4bd7-11e8-954b-17a1c4d07096.png)

```
python splatnet2statink.py
splatnet2statink v1.1.1
There is a new version available.
Would you like to update now? [Y/n] n
Remember to update later with "git pull" to get the latest database.
Pulling data from online...
Number of recent battles to upload (0-50)? 3
Traceback (most recent call last):
  File "splatnet2statink.py", line 1167, in <module>
    post_battle(i, results, is_s, is_t, m_value, True if i == 0 else False, debug)
  File "splatnet2statink.py", line 980, in post_battle
    payload = set_scoreboard(payload, bn, mystats, s_flag)
  File "splatnet2statink.py", line 699, in set_scoreboard
    "top_500":        full_scoreboard[n][16],
IndexError: list index out of range
```

**Comment by clovervidia** [comment]
Hmm, I missed that. Seems we will have to try/except every usage of `crown_players` and other X-rank fields. I just pushed another update to that branch, can you try it again?

**Comment by pixelyunicorn** [comment]
It seems to work! 

![image](https://user-images.githubusercontent.com/607807/39411459-9987a260-4bd8-11e8-89c5-74703fa16af8.png)

**Comment by clovervidia** [comment]
Fantastic! I made one more change to handle the missing field in the place where the payload array is assembled rather than three separate times to minimize errors if we have to make further changes to `crown_players`, so if you wouldn't mind testing that as well. If this works, I can merge this into master and get this rolled out.

**Comment by clovervidia** [comment]
Appreciate the testing. I'm going to run some final tests on it to (hopefully) make sure there aren't any other missing fields in other modes that aren't being handled, and then I'll merge it into master later today. If anything else that could be related to v3.0.0 features comes up, definitely leave a comment here.

**Comment by clovervidia** [comment]
I've merged the branch into master so it should be rolling out to users shortly. I'm going to close the issue, but again if anything else breaks, feel free to comment and reopen it.
