### ISSUE TITLE
Add a flag that automatically upgrades the script / ignores it

### ISSUE THREAD

**Issue by Josephvb10** [frozenpandaman/splatnet2statink#50]
Hello.

I currently use the script in a from service that runs the .py file with the -r flag. However if there's an update the script doesn't run as it keeps waiting for user input (Do you want to upgrade?).

That's why I'm asking for a new flag that skips the upgrade or automatically upgrades and re-runs the script with the same flags, this would allow to keep the cron running forever without user intervention every time there's an update.

**Comment by frozenpandaman** [comment]
Would @fetus-hina's solution work for you?

https://github.com/frozenpandaman/splatnet2statink/issues/30#issuecomment-358103518

The way he does it, [`/bin/yes`](https://en.wikipedia.org/wiki/Yes_(Unix)) gets piped into the program so the update prompt is automatically answered (i.e. the script automatically updates).

**Comment by frozenpandaman** [comment]
@Josephvb10 Have you had a chance to try this yet?

**Comment by Josephvb10** [comment]
It works so I'm closing this, but an auto-update option should be considered still!

**Comment by frozenpandaman** [comment]
I'd consider adding a [custom key](https://github.com/frozenpandaman/splatnet2statink/wiki/custom-keys) to allow suppression of console output.
