### ISSUE TITLE
Nintendo Switch Online v1.4.1 update

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/splatnet2statink#56]
To look into & update user agent info in iksm.py. Let's hope it doesn't break anything…

**Comment by frozenpandaman** [comment]
https://github.com/frozenpandaman/splatnet2statink/blob/0c150ca524a0c9748e4d607281717d4d6f91da30/iksm.py#L61

Changed to "Select this person"
![image](https://user-images.githubusercontent.com/7245874/45574439-e085d200-b824-11e8-8f8b-879190a0c709.png)

**Comment by frozenpandaman** [comment]
Autologin still works! So I think the only thing to do is update the user agent.

https://github.com/frozenpandaman/splatnet2statink/blob/0c150ca524a0c9748e4d607281717d4d6f91da30/iksm.py#L80

**Comment by frozenpandaman** [comment]
v1.4.1 adds certificate pinning, so mitm no longer works. v1.1.2 and below still work.

**Comment by edmiyaa** [comment]
> v1.4.1 adds certificate pinning, so mitm no longer works. v1.1.2 and below still work.

I'm having this problem right now, I was trying to extract the iksm_session key as I did many times before, but then I realized that it seemed to ignore the mitmproxy certificate. So, what would be the solution? Downgrade the app and try again?

**Comment by frozenpandaman** [comment]
@edmiyaa Yup. Manually install the 1.1.2 apk and use that. I updated the [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) to say this as well. (Hopefully this version will keep being supported, and Nintendo won't force you to upgrade…) Or, use splatnet2statink automatic cookie generation and you can generate an `iksm_session` cookie right from your computer instead of having to go through the app!

**Comment by edmiyaa** [comment]
Alright thanks! I'll try splatnet2statink and see how it goes.

**Comment by frozenpandaman** [comment]
Bizarrely, @clovervidia says it's still working for him using v1.4.1 of the app:
![image](https://user-images.githubusercontent.com/7245874/45615214-b698ff00-ba20-11e8-8de0-5a04c169a9a8.png)

But it's still not for me – or @edmiyaa, evidently.

I tried with Charles Proxy (couldn't get Fiddler's Mac version to work) to verify it wasn't some mitmproxy issue to also no luck:
![image](https://user-images.githubusercontent.com/7245874/45615289-f2cc5f80-ba20-11e8-9458-db0d747b6e63.png)

It may have worked for @clovervidia since he's on a version of Android lower than 7.0…?
![image](https://user-images.githubusercontent.com/7245874/45615425-4f2f7f00-ba21-11e8-85d6-6d5fcc638716.png)

🤔

**Comment by Tiryoh** [comment]
I'm not sure about this, but it seems like v1.1.2 client is not working for now.
```
$ ./splatnet2statink.py -r
splatnet2statink v1.1.9
The stored cookie has expired.
Attempting to generate new cookie...
Error from Nintendo:
{
  "status": 9427,
  "errorMessage": "Upgrade required.",
  "correlationId": "9456d333-6f1d3460"
}

$ git log
commit 186ba89cb67d9bd03dc41b23bdf768db237004cc (HEAD -> master, upstream/master)
```

Writing `config.txt` manually by using v1.4.0 app (iOS) + mitmproxy worked fine.
<img width="1222" alt="_2018-09-18_15_40_08" src="https://user-images.githubusercontent.com/3256629/45668963-7c7f4880-bb59-11e8-851e-1efac65e824b.png">

**Comment by frozenpandaman** [comment]
Was just about to post, and talked about this with @hymm earlier too… Yup, old versions of the app are now no longer allowed. Changing the user agent to 1.4.1 (or 1.4.0 as that's the current version for iOS) fixes the "Upgrade required" error, naturally, but then it changes to "Bad request": 
![image](https://user-images.githubusercontent.com/7245874/45669764-da6a4c80-bad5-11e8-81bd-562590612e49.png)

It appears `f` has changed. 🙁

Great that you can still use mitmproxy on iOS. I think it's blocked on Android 7.0 and up, which certainly is an issue…

**Comment by Tiryoh** [comment]
> It appears the key used to generate the f HMAC has changed. 🙁

Oh... 
Thanks for the information.  I will use the iOS app + mitmproxy for the time being.

**Comment by frozenpandaman** [comment]
Network Security Configuration is what prevents mitmproxy from now working in Android 7.0 and higher. More info [here](https://developer.android.com/training/articles/security-config) and [here](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html). I installed the app on an emulator running an older version of android and I'm now able to mitm the requests fine.

---

There have been some changes to `/v1/Account/Login`, namely introducing two new parameters:
```
"requestId": "123e4567-e89b-12d3-a456-426655440000",
"timestamp":1537249847
```

That's a UUID version 4 and unix (epoch) timestamp. When these are included, the error changes from "Bad request" to "Invalid token":
![image](https://user-images.githubusercontent.com/7245874/45676369-6edcab00-bae6-11e8-97dc-06f9c95a7e26.png)

**Comment by YDKK** [comment]
It seems they generate new `f` parameter in the native library, which is difficult to analysis. 😞

**Comment by hymm** [comment]
I decompiled the so, but can't really read assembly :'(

**Comment by frozenpandaman** [comment]
Yeah, I played around with some tools too – [apktool](https://ibotpeaches.github.io/Apktool/), [dex2jar](https://github.com/pxb1988/dex2jar), [IDA Free](https://www.hex-rays.com/products/ida/support/download_freeware.shtml), [RetDec](https://retdec.com/) – and got the disassembly of `gen_audio_h` within (x86) `libvoip.so` as well… but this is so far outside my area of knowledge I don't know how to proceed. :x

**Comment by frozenpandaman** [comment]
Yeah, I played around with some tools too – [apktool](https://ibotpeaches.github.io/Apktool/), [dex2jar](https://github.com/pxb1988/dex2jar), [dnSpy](https://github.com/0xd4d/dnSpy), [IDA Free](https://www.hex-rays.com/products/ida/support/download_freeware.shtml), [RetDec](https://retdec.com/) – and got the disassembly of `gen_audio_h` within (x86) `libvoip.so` as well… but this is so far outside my area of knowledge I don't know how to proceed. :x

**Comment by edmiyaa** [comment]
So, what is the impact of not knowing how to generate the `f` parameter? It only affects the _automatic_ generation of the `iksm_session` cookie right? For now I'm doing it manually (older version of the app together with mitm proxy), but I'm worried when Nintendo starts forcing to use the latest version of the app.

**Comment by hymm** [comment]
@edmiyaa You can use an older version of android like on the Nox emulator with the latest version of the app.

**Comment by edmiyaa** [comment]
@hymm Thanks! I'll keep that in mind.

**Comment by chrhasse** [comment]
I don't think it's that the app implemented certificate pinning, but rather that the app now targets a more recent API level (since google now requires that), and more recent API levels not trusting user certificates (only system certificates) by default.

If you use Magisk you can just install [this module](https://github.com/NVISO-BE/MagiskTrustUserCerts) to trust user certs.

If you have root you can also install the mitm certificate as a root certificate by naming it with the output of `openssl x509 -noout -subject_hash_old -in ~/.mitmproxy/mitmproxy-ca-cert.pem` followed by `.0` (for example `c8450f0d.0`), and copying it to `/etc/security/cacerts/`. you might need to remount system as read/write before you can copy it.

Without root you can also use [this tool](https://github.com/levyitay/AddSecurityExceptionAndroid) to modify the APK to use additional certificates from a specified path. 

This info is mostly taken from [this thread](https://github.com/mitmproxy/mitmproxy/issues/2054) if anyone wants more discussion on this.

**Comment by frozenpandaman** [comment]
@chrhasse Oooh yeah, you're totally right. @YDKK was saying he didn't find any evidence of cert pinning either… and if they did add it, it'd be weird for mitmproxy to still work with the newest version of the app on older Android versions. That's also supported by [this announcement](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)… plus 
[this email](https://user-images.githubusercontent.com/7245874/45926810-5a7d2180-bedd-11e8-914e-248c4e6235d8.png) I got from Google a few days ago. :P I'll update the docs for accuracy – thanks!

I can't root my phone (thanks Verizon for locking the bootloader on my Pixel!) but those are good resources to have! I'll look into the tool you linked, and thanks for the link to the thread on the mitmproxy repo as well. None of these methods of are of course *ideal* though – there are for sure multiple workarounds, but at this point what I'm really hoping for is to figure out the new way `f` is generated… though, again, it's proving pretty tough. 😣

**Comment by Valerokai** [comment]
@frozenpandaman Does the app work in an emulator? You could try using a rooted android emulator, and then using mitmproxy on that.

**Comment by frozenpandaman** [comment]
@Valerokai Doesn't even need to be rooted – mitmproxy works fine as long as you're running a version of Android below 7.0. (The [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) have said this & have suggested an emulator to use for a few days now as well. 😜)

Getting your cookie manually like that has always been possible (and always should be). It's just the [generation](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs#how-it-works) that is broken now – i.e. the splatnet2statink returns `f` values that no longer work – because we don't know how the new `f` is generated.

**Comment by frozenpandaman** [comment]
`f` can now be different lengths (here are 10 examples):
![image](https://user-images.githubusercontent.com/7245874/45932363-b7a1c300-bf2f-11e8-9f8e-6dba14834866.png)

So it's likely not an HMAC/hash function anymore… 🙃

On the bright side, the DLLs in the iOS .ipa aren't obfuscated (via Dotfuscator :B) like those in the .apk are, at least. But not even sure that helps, really.

**Comment by chrhasse** [comment]
Is there a way to get the ipa file without an iOS device? if it's not obfuscated it would definitely be easier for me to look at

**Comment by frozenpandaman** [comment]
@chrhasse I downloaded it from my (very old) jailbroken iPod and didn't have any trouble opening that file. I don't see any contact info on your GitHub profile, so DM me on Twitter. :)

**Comment by vlee489** [comment]
Any chance I could get my hand on those files @frozenpandaman , I haven't been able to use mitm cause university internet and I left my jailbroken iPod/rooted S4 back home >.<

**Comment by vlee489** [comment]
This update broke my work on splatstats.ink

**Comment by frozenpandaman** [comment]
Oops, I tried to combine your multiple comments in a row into one and GitHub decided to let everybody know about it lol. Sorry about that.

Anyway, @vlee489, I'm not familiar with the project but it doesn't look like it's public yet. Isn't weapon usage & team stats something @hymm's http://squidtracks.ink/ already does? 

Re: the .ipa see my above comment.

**Comment by vlee489** [comment]
yeah but I'm adding some data analysis into what squidtracks itself has. I'm still working on the code that does the comparing and displaying of data, just d3.js last update broke a ton of my code for the data visualisation part of my website. 

my main issue is that I can't access splatnet to download the weapon data anymore and I can't use mitmproxy on my Uni network to do the reverse engineering work.

**Comment by frozenpandaman** [comment]
Well, hopefully we can figure out stuff soon (it took multiple months previously, when `f` was introduced for the first time 😉) so you can continue work on it.

(A bit off-topic now, but what if you make a Wi-Fi hotspot from your phone, connect your computer to it, and then use an Android emulator?)

splatoon2.ink has a few API endpoints for making things like stage rotation, salmon run schedule, gear shop, etc. public, i.e. taking the data from the app's `iksm_session`-required API endpoints, cleaning them up a bit, and making it accessible through a new URL. You could ask @misenhower if he would want to make one for League data, too, which would prevent you from having to use your own cookie.

**Comment by vlee489** [comment]
(I can't really efficiently run Hyper-V on top of KVM, saying that I already have a makeshift router in my room working on rerouting my switch to get my switch to play online)

I could ask @misenhower about making an API endpoint but, there are 72 league sets day to get (96 if you include ALL), and that's a lot to cache and make sure they are valid. plus I pull more in then just league data to make things work.

**Comment by clovervidia** [comment]
@vlee489 I might be able to help if you're looking for ways to get league leaderboard data. Do you have a preferred way to DM, like Twitter or Discord?

**Comment by frozenpandaman** [comment]
Moving main discussion of `f` generation to #62. Keeping comments unlocked here in case there is further discussion around related issues or continued conversations from earlier.
