### ISSUE TITLE
f token generation in NSO app v1.4.1

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/splatnet2statink#62]
(Migrating from #56 where the discussion got a bit messy and where we were still figuring out specifics of the situation.)

The `f` token was introduced into the Nintendo Switch Online app last year in v1.1.0 as a parameter that must be sent in the request to Nintendo to generate an `iksm_session` cookie, which grants access to app.splatoon2.nintendo.net and thus a user's battle log. We were able to figure out the generation method and create an [API](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs) to return the `f` value for a given input.

In v1.4.1 of the app, `f` is generated in a new, as-of-yet unknown way. Tokens appear to be in a slightly different form, and requests sent with the old-style `f` tokens now return an "Invalid token." response. Users may still [use mitmproxy](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) to obtain `iksm_session` cookies manually via sniffing app traffic, but this is not a solution or ideal experience.

**If you can help with reverse engineering the app and figuring out how `f` tokens are generated, please reach out via [Twitter](https://twitter.com/frozenpandaman).**

This issue will stay open until `f` generation is once again solved or deemed practically impossible/unfeasible.

**Comment by frozenpandaman** [comment]
Apparently a solution has been found by the ikaWidget2 dev… have reached out for more info… https://twitter.com/NexusMine/status/1051500912584273920

**Comment by frozenpandaman** [comment]
ikaWidget2 created their own API where they fixed f generation which behaves in the same way as mine did previously: `https://flapg.com/ika2/api/login`

Not sure if the creator is intending others apart from their app to use it, and there's no public mention of it existing, or any docs, etc… so I DMed them, having talked in depth with them about this before. But either way, we should be able to integrate this shortly (granted we can figure out what valid requests are) to get autologin working again.

**Comment by frozenpandaman** [comment]
The ikaWidget2 dev created their own API where they fixed f generation which behaves in almost the same way as mine did previously: `https://flapg.com/ika2/api/login`

Not sure if the creator is intending others apart from their app to use it, and there's no public mention of it existing, or any docs, etc… so I DMed them, having talked in depth with them about this before. But either way, we should be able to integrate this shortly (granted we can figure out what valid requests are) to get autologin working again.

**Comment by Dog2puppy** [comment]
Any update on this? My token keeps expiring and it’s annoying having to reset it.

**Comment by frozenpandaman** [comment]
@Dog2puppy Nope. I sent a message specifically mentioning their API & asking if we could use it (and if so, how) on November 1, and haven't heard back yet. It's of course not the ideal solution, but I'm able to very easily get new tokens in ~1 minute using the Nox App Player Android emulator + mitmproxy. I can make a gif showing my workflow if you'd like.

**Comment by Dog2puppy** [comment]
If they say yes, does that mean no more worrying about the token expiring like once a week?

**Comment by frozenpandaman** [comment]
Yes, it'll go back to how it was before, with the script being able to generate them automatically as-needed from your `session_token` saved in `config.txt`. The [api docs](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs) wiki page has more information. I'd like to keep discussion on this issue focused around specifically how to solve `f` generation – so, for further questions, please post in #56.

**Comment by genesis424** [comment]
> @Dog2puppy Nope. I sent a message specifically mentioning their API & asking if we could use it (and if so, how) on November 1, and haven't heard back yet. It's of course not the ideal solution, but I'm able to very easily get new tokens in ~1 minute using the Nox App Player Android emulator + mitmproxy. I can make a gif showing my workflow if you'd like.

I would super appreciate a gif showing your process if that's possible!

**Comment by frozenpandaman** [comment]
@genesis424 
![s2s](https://user-images.githubusercontent.com/7245874/48129730-33856f80-e23f-11e8-9e96-3ae37f9477c5.gif)

**Comment by frozenpandaman** [comment]
![image](https://user-images.githubusercontent.com/7245874/52111777-7abe9a80-25b9-11e9-944c-5d5a6a273cd6.png)
### WE'RE &nbsp;B A C K

**Comment by frozenpandaman** [comment]
Massive thanks to [@NexusMine](https://twitter.com/NexusMine) for setting up an Android emulator of the app on his server (the flapg URL above. I don't 100% understand this part but hey, what can you do) and giving me information on how to use it.

I've updated the splatnet2statink API to be used *in conjunction* with the flapg API. The s2s API's function has also changed: it now generates *hashes* (not `f` values) using a specific algorithm. This hash must then sent to the flapg API, along with some other headers, in order to generate an `f`… which then, as before, is finally sent in a request to Nintendo's servers to get back an `iksm_session` cookie.

The API docs page will be updated shortly (not looking forward to re-LaTeXing that diagram and making it even more complicated…) and the fix released & made public!!! 😄

**Comment by guigas7** [comment]
Thanks a lot. I just got a phone that can open the switch app but i couldn't make it work with mitmproxy. I'm getting an error code 2817-0599. The switch app says the connection is unstable and i can't use splatnet at all.

**Comment by frozenpandaman** [comment]
@guigas7 Please make sure you're reading the note on top of the [mitmproxy instructions](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions) page, as this explains why it won't work if your phone is running Android 7.0 or higher, and provides a workaround. With automatic login working again, though, you won't need to use mitmproxy at all.

As your issue isn't related to autologin/`f` generation, please post any follow-up questions or discussion of this in #64 instead.

**Comment by frozenpandaman** [comment]
The fix is now live! 😄 0590ac7
