### ISSUE TITLE
Support uploading Salmon Run shifts

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/splatnet2statink#63]
For reference in case stat.ink ever allows uploading these stats. Irrelevant keys (e.g. `image`, `thumbnail`, `name` if `id` exists) have been removed.

<pre><b>https://app.splatoon2.nintendo.net/api/coop_results</b>
├── results
│   └── (see below) – but does NOT include other_results
├── reward_gear                           This month's gear         
│   └── id
└── summary                               Last 50 battles summary
    ├── card
    │   ├── golden_ikura_total            Golden Eggs collected
    │   ├── help_total                    Crew members rescued
    │   ├── ikura_total                   Power Eggs collected
    │   ├── job_num                       Shifts (jobs) worked
    │   ├── kuma_point                    Current points
    │   └── kuma_point_total              Total points
    └── stats (list)
        ├── 0                             Shift (job) #1 data
        │   ├── clear_num                 Jobs cleared
        │   ├── dead_total                Total deaths
        │   ├── end_time                  Epoch rotation end time
        │   ├── failure_counts (list)
        │   │   ├── 0                     Wave 1 fail count
        │   │   ├── 1                     Wave 2 fail count
        │   │   └── 2                     Wave 3 fail count
        │   ├── grade
        │   │   └── id                    Title, e.g. 5 = Profreshional
        │   ├── grade_point               Rank (number after title)
        │   ├── help_total                (Total) Crew members rescued
        │   ├── job_num                   Number of jobs worked in rotation
        │   ├── kuma_point_total          (Total) Grizzco Points
        │   ├── my_golden_ikura_total     (Total) Golden Eggs personally collected
        │   ├── my_ikura_total            (Total) Power Eggs personally collected
        │   ├── schedule
        │   │   ├── end_time              Epoch rotation end time
        │   │   ├── stage
        │   │   │   ├── name              Stage name, e.g. Lost Outpost
        │   │   │   └── image             Stage image URL
        │   │   ├── start_time            Epoch rotation start time
        │   │   └── weapons (list)        Weapon list
        │   │       ├── 0
        │   │       │   └── id            -2 = Grizzco random, -1 = regular random
        │   │       ├── 1
        │   │       │   └── id
        │   │       ├── 2
        │   │       │   └── id
        │   │       └── 3
        │   │           └── id
        │   ├── start_time                Epoch rotation start time
        │   ├── team_golden_ikura_total   (Total) Golden Eggs collected
        │   └── team_ikura_total          (Total) Power Eggs collected
        ├── 1                             Shift (job) #2 data
        │   └── ...
        └── ...
</pre>

<pre><b>https://app.splatoon2.nintendo.net/api/coop_results/[job number]</b>
├── boss_counts
│   ├── 3
│   │   ├── boss
│   │   │   └── key                sakelien-golden
│   │   └── count                  # of Goldie appearances
│   ├── 6
│   │   ├── boss
│   │   │   └── key                sakelien-bomber
│   │   └── count                  # of Steelhead appearances
│   ├── 9
│   │   ├── boss
│   │   │   └── key                sakelien-cup-twins
│   │   └── count                  # of Flyfish appearances
│   ├── 12
│   │   ├── boss
│   │   │   └── key                sakelien-shield
│   │   └── count                  # of Scrapper appearances
│   ├── 13
│   │   ├── boss
│   │   │   └── key                sakelien-snake
│   │   └── count                  # of Steel Eel appearances
│   ├── 14
│   │   ├── boss
│   │   │   └── key                sakelien-tower
│   │   └── count                  # of Stinger appearances
│   ├── 15
│   │   ├── boss
│   │   │   └── key                sakediver
│   │   └── count                  # of Maws appearances
│   ├── 16
│   │   ├── boss
│   │   │   └── key                sakedozer
│   │   └── count                  # of Griller appearances
│   └── 21
│       ├── boss
│       │   └── key                sakerocket
│       └── count                  # of Drizzler appearances
├── danger_rate                    Hazard level (5-200)
├── end_time                       Epoch rotation end time
├── grade
│   └── id                         Title, e.g. 5 = Profreshional
├── grade_point                    Rank after end
├── grade_point_delta              How much rank changed
├── job_id                         Shift (job) ID #
├── job_rate                       Pay grade %
├── job_result
│   ├── failure_reason             wipe_out, time_limit, null
│   ├── failure_wave               1, 2, 3, null
│   └── is_clear                   true/false
├── job_score                      Job Score
├── kuma_point                     Grizzco Points
├── my_result
│   ├── boss_kill_counts
│   │   └── ... (mirrors boss_counts)
│   ├── dead_count                 # of deaths
│   ├── golden_ikura_num           Golden Eggs collected
│   ├── help_count                 # of revivals
│   ├── ikura_num                  Power Eggs collected
│   ├── name                       Nickname
│   ├── pid                        Player ID
│   ├── special                    Assigned Special weapon
│   │   └── id
│   ├── special_counts (list)
│   │   ├── 0                      # of Specials used in wave 1
│   │   ├── 1                      # of Specials used in wave 2
│   │   └── 2                      # of Specials used in wave 3
│   └── weapon_list (list)
│       ├── 0                      Weapon assigned in wave 1
│       │   └── id
│       ├── 1                      Weapon assigned in wave 2
│       │   └── id
│       └── 2                      Weapon assigned in wave 3
│           └── id
├── other_results (list)
│   ├── 0
│   │   └── ... (mirrors my_result)
│   ├── 1
│   │   └── ...
│   └── 2
│       └── ...
├── play_time                      Epoch shift (job) start time
├── player_type
│   ├── species                    inklings, octolings
│   └── style                      girl, boy
├── schedule
│   └── ... (same as summary>stats>schedule)
├── start_time                     Epoch rotation start time
└── wave_details (list)
    ├── 0                          Wave 1
    │   ├── event_type
    │   │   └── key                cohock-charge, fog, water-levels, etc.
    │   ├── golden_ikura_num       Golden Eggs Collected
    │   ├── golden_ikura_pop_num   Golden Egg appearances
    │   ├── ikura_num              Power Eggs collected
    │   ├── quota_num              Golden Egg quota (# required)
    │   └── water_level
    │       └── key                low, normal, high
    ├── 1                          Wave 2
    │   └── ...
    └── 2                          Wave 3
        └── ...
</pre>

**Comment by frozenpandaman** [comment]
Values to figure out:

- [ ] `failure_reason`: `wipe_out`, null
  - Need: quota not met
- [x] `grade`>`id`: `5` = Profressional
  - Assuming `4` = Overachiever, `3` = Go-Getter, `2` = Part-Timer, `1` = Apprentice
  - Is Intern `0`? Does it even show up?
- [x] `water_level`>`key`: `low`, `normal`, `high`
- [ ] `event_type`>`key`: `cohock-charge`, `fog`, `water-levels (normal)`
  - Need: chum rush, goldie seeking, griller, mothership

**Comment by frozenpandaman** [comment]
Adding support in the [`salmon-run` branch](https://github.com/frozenpandaman/splatnet2statink/tree/salmon-run)…

![image](https://user-images.githubusercontent.com/7245874/46522175-ede81800-c836-11e8-9288-2c61630d3e70.png)
![image](https://user-images.githubusercontent.com/7245874/46522185-f2accc00-c836-11e8-8e6e-b19719fc49f1.png)

**Comment by frozenpandaman** [comment]
`salmon-run` branch is fully up-to-date, working, and ready to merge, pending stat.ink API updates & a little more testing!

**Comment by fetus-hina** [comment]
Just a note: "intern" jobs are probably not recorded. (It doesn't affected to our apps)
https://stat.ink/@20excalibur07/salmon/1049
This is "job # 1" and "Apprentice 40→60".

**Comment by frozenpandaman** [comment]
That's what I assumed – good to be able to confirm! Thanks!
