### ISSUE TITLE
mitmproxy not working

### ISSUE THREAD

**Issue by Terax235** [frozenpandaman/splatnet2statink#64]
I'm trying to get an iksm_token using [this guide](https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions), but it doesn't seem to work.

I've started `mitmweb` and changed the Wifi settings on my iOS, then I tried to get to http://mitm.it/ but after a while it says that the server doesn't respond. What did I do wrong?

**Comment by marijnvdwerf** [comment]
Quick list of things that might have went wrong:
- Did you save the settings after making the change? (top right)
- Have you input the correct port (8080)
- Are you sure the IP-address matches and is reachable from the wireless network

**Comment by frozenpandaman** [comment]
Also make sure your phone and computer are on the same Wi-Fi network. If you still encounter problems, I'd try a different network if you can (e.g. I'd expect some public or workplace network configs to not work).

**Comment by Terax235** [comment]
I'm sure. Could the problem be that my PC is connected over LAN but my mobile over WiFi?

**Comment by frozenpandaman** [comment]
Not 100% sure on this because I've never tested it myself and don't know a lot about networking stuff, but that sounds like it's probably the issue. They should both be on Wi-Fi and on the same network, so your computer's internal IP is accessible through your phone.

**Comment by Terax235** [comment]
Windows 10 @marijnvdwerf

**Comment by frozenpandaman** [comment]
@Terax235 Were you able to try with a computer connected to that same Wi-Fi network?

**Comment by Terax235** [comment]
@frozenpandaman I'm now trying to do this on my laptop which is connected to the same Wi-Fi network.

**Comment by frozenpandaman** [comment]
Closing as been two days since an update and it's not related to splatnet2statink. Feel free to post here if you can't figure out further issues.

**Comment by Terax235** [comment]
I'm sorry for responding very late, but I've tested it and there are the results:
The certificate doesn't install on my iOS. There is no option to enable full trust for root certificates.

**Comment by Terax235** [comment]
It's opening the page http://mitm.it/ but there's no certificate listed.
