### ISSUE TITLE
Possible bug on salmon mode

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/splatnet2statink#75]
So, running the script with ./splatnet2statink.py --salmon on linux prints an html page [out.txt](https://github.com/frozenpandaman/splatnet2statink/files/2896891/out.txt)
 if i select a number of shifts to upload that is higher than the amount of shifts not uploaded i have. If i ask to upload more than 1 overflowing shift (if i have 1 shift not uploaded and i ask to upload more than 2) it prompts to continue and it just keeps printing it again if i say yes.

![screenshot from 2019-02-23 11-45-13](https://user-images.githubusercontent.com/11247506/53287843-83d9fc00-3760-11e9-9921-85f5bc1065cc.png)

![screenshot from 2019-02-23 11-47-20](https://user-images.githubusercontent.com/11247506/53287867-ca2f5b00-3760-11e9-9944-9efe74d16140.png)

**Comment by frozenpandaman** [comment]
Ah, looks like it's printing the page contents rather than the returned "hey this battle exists online already, and here's where" URL. I can look into this tomorrow. Thanks!

**Comment by frozenpandaman** [comment]
OK, finally had time to look into this & was able to replicate it… it seems stat.ink is returning an HTTP 200 OK response rather than a 302 (redirect) when uploading an already-uploaded job. Hina is looking into this shortly so we can fix it.
