### ISSUE TITLE
f token no longer needed?

### ISSUE THREAD

**Issue by Jetsurf** [frozenpandaman/splatnet2statink#77]
Hello,

I've been working on a discord bot to pull data from splatnet and came across the following realization. While adapting the code from your projects token grabber to my bots code, I came across an "error". I wasn't leveraging the flapg api, but was still getting back 200OK responses from Nintendo when getting the iksm_session token. At first, I was just thinking I implemented everything correctly, but digging deeper, I found out I wasn't setting this f token up properly. I even went as far as sending "None" as a token to Nintendo AND STILL got back 200 OK responses from them with valid iksm_session tokens. I've gotten tokens for 7 discord members multiple times so far following this method.

Here is a link to the file with my version of the code: https://github.com/Jetsurf/jet-bot/blob/master/nsotoken.py

(Specifically line 128, I can put in debug prints for the entire chain into my bot and give you proof of the behavior I'm claiming)

Wasn't sure if this was the right place to post this, but I wanted to see if any of you have noticed the same thing going on? Really bizarre and might make things easier for your project.

**Comment by clovervidia** [comment]
This is a very interesting discovery indeed. I tried it out myself by modifying `iksm.py` to force `f` to be `None`, like in your `nsotoken.py`, and it worked for me. I was able to log in to my account without needing `f` or using the `flapg` API.  
That being said, I'd be a little wary of them changing how authentication works. They haven't updated the app recently, which means the app is probably still sending `f` tokens, so it's possible this is an oversight somewhere that might be corrected at any time. But it would make authentication easier, so I don't see any reason not to use it as long as preparations are made to roll back to using the `flapg` API if they start requiring `f` again.

**Comment by Jetsurf** [comment]
Thanks for the confirmation. I'm still scratching my head as to why this change happened. That said, if this requires the f token again in the future, is there a way I can leverage the flapg api with my bot to get these f tokens and be OK? It seems its specifically meant for use with this project, but if I generate an s2s account and get the hash to return an f token for my bot use to get iksm for multiple users, is that considered abuse?

**Comment by frozenpandaman** [comment]
Interesting. Thanks for letting us know! (I can't try it out as I'm out of town/away from my computer for the next couple of weeks.)

It sounds like the app is most likely (could confirm by mitm-ing) still sending `f` tokens itself and for some reason their servers – possibly unintentionally – just aren't requiring them in requests, at least for the time being…

I don't think removing the flapg API call would actually change the login UX for our users in any way, but we should wait a few weeks to see if anything changes on Nintendo's end before changing up our stuff.

**Comment by Jetsurf** [comment]
No problem! I did indeed check with mitm myself before I implemented the token grabber and saw f still being passed.

**Comment by clovervidia** [comment]
I was going to suggest maybe there is an app update coming soon that removes or otherwise dummies out `f` for whatever reason, but if this has been going on for half a month, that's some oversight and the update should've been pushed by now. As far as matching the app's behavior, that makes sense, and yet at the same time, I'm sure it looks pretty suspicious to see the same traffic patterns coming from the same accounts using the same one user agent.

**Comment by frozenpandaman** [comment]
Closing as I don't plan on changing the script's behavior at this time and there's no real "issue," but we can still discuss here going forward if needed. :)

**Comment by frozenpandaman** [comment]
https://github.com/frozenpandaman/splatnet2statink/issues/79#issuecomment-482386999
