### ISSUE TITLE
f token generation changed in NSO app v1.5.0

### ISSUE THREAD

**Issue by Jetsurf** [frozenpandaman/splatnet2statink#79]
Hello again guys.

I noticed an update hit for the NSO app. Looks like f token generation changed completely. The new tokens appear to be longer than in 1.4.1.

1.5.0.1 token
`"f": "53ac761c0b943a2053bd434bbcb85b62c43165b89ce63f8bd65d1becb852bbccdcf3caaf3bbddd6b97"`

As compared to 1.4.1
`'f': '28b3aa6dd762fbfcf114a348d8da17fb382c4b8e'`

Just giving a heads up as I won't have time in the near future to look into this; but, this appears to be the reason that they weren't doing the f token checks that I originally reported.

**Comment by frozenpandaman** [comment]
Yup, someone just reported this this morning as well: https://twitter.com/BOQ_JP/status/1116360750363054082

I hadn't noticed the app update on the 8th. Will look into it tonight. Hopefully it'll be fixed & go back to working by just updating the version number in the request headers. :)

**Comment by Jetsurf** [comment]
Just a heads up on that front. I changed the version numbers from 1.4.1 to 1.5.0.1 in my project as well as yours. Token errors occur rather than just the "Update Required" response.

**Comment by frozenpandaman** [comment]
Yup, someone just reported this this morning as well: https://twitter.com/BOQ_JP/status/1116360750363054082

I had hoped that simply updating the version number in the request headers would work (wishful thinking) – but as you pointed out it appears the `f` token format was changed too... again... so hopefully the flapg API can fix this soon, I'll let them know about the change as well.

**Comment by clovervidia** [comment]
Probably obvious by now, but blank `f` tokens no longer work:

```json
Error from Nintendo:
{
  "correlationId": "7cb47dc8-beeeab8d",
  "errorMessage": "Bad request.",
  "status": 9400
}
```

**Comment by frozenpandaman** [comment]
NexusMine, the maintainer of the flapg API, is currently investigating/working on a solution, but says it may take some time: https://twitter.com/NexusMine/status/1116919063568011265

**Comment by issei-m** [comment]
Looks like f token generation api came back?
https://twitter.com/NexusMine/status/1122704397115346944

**Comment by frozenpandaman** [comment]
@issei-m Yup, he messaged me a few hours ago too. Was planning to get to it later tonight. 😉

**Comment by frozenpandaman** [comment]
Wow, Nintendo changed stuff up quite a bit, introducing a new `f` token and some other stuff at a different point in the login process. (I don't think I'm going to re-TeX that diagram on the API docs page for a third time, tbh…)

Working now. :) Will make it live soon.

```
$ ./splatnet2statink.py 
splatnet2statink v1.5.0
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Wrote iksm_session cookie for eli to config.txt.
Pulling data from online...
Number of recent battles to upload (0-50)? 
```

(Going to take a few days to get the executable versions updated though, but doubt that'll be of concern to too many people here…)

**Comment by frozenpandaman** [comment]
Hah, now both the NSO app and this script are version 1.5.0. :P
