### ISSUE TITLE
Cannot open NSO app using mitmproxy

### ISSUE THREAD

**Issue by Wolfy76700** [frozenpandaman/splatnet2statink#82]
With the latest version, NSO now only supports Android 5.0 and above, meaning I had to install Android 5.0 in Nox. However, I cannot get it to connect to the internet through mitmproxy anymore, despite me putting the right address as a proxy. Any ideas on how to solve this?

**Comment by frozenpandaman** [comment]
Hmm, I just re-installed Nox a few days ago and it worked fine for me with the version of Android Nox comes with by default (4.4.2). I can look into this more tomorrow.

**Comment by Wolfy76700** [comment]
OK, I checked and I just forgot to install the mitmproxy certificate in the emulated version of Android 5.0, and now it works

**Comment by Wolfy76700** [comment]
Also, as a side note, I've managed to access Smash World on https://app.smashbros.nintendo.net/ by grabbing the "super_smash_session" value of the cookie and inputting that in Firefox
