### ISSUE TITLE
Error from the flapg API: Error 404 (incorrect headers)

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/splatnet2statink#86]
Just had this.
![image](https://user-images.githubusercontent.com/11247506/60628348-78aa7300-9dc7-11e9-9c33-4956fc34fd00.png)
I tried removing my config.txt and reentering the api key and all that but i'm still getting the same error

**Comment by guigas7** [comment]
splat is just an alias
![image](https://user-images.githubusercontent.com/11247506/60628500-0a19e500-9dc8-11e9-8840-a8041661a464.png)

**Comment by frozenpandaman** [comment]
Reported on Twitter earlier as well: https://twitter.com/tkgling/status/1146435612808867840

Something must've changed on the flapg API end of things... I've reached out to NexusMine for more information.

**Comment by frozenpandaman** [comment]
The server just went down. It should be back up soon.
