### ISSUE TITLE
Specific battle fails to upload (fest exp must be an integer)

### ISSUE THREAD

**Issue by 466gaming** [frozenpandaman/splatnet2statink#88]
When trying to upload a specific battle, this error message shows up:
![image](https://user-images.githubusercontent.com/17676761/61503448-ba463b00-a9cf-11e9-8830-3ded5a1ff624.png)
No other battle (so far) has had this issue.
I don't know if it's of any use, but here's the battle stats from SplatNet 2:
![image](https://user-images.githubusercontent.com/17676761/61503553-098c6b80-a9d0-11e9-8e9f-8f496304b12e.png)
![image](https://user-images.githubusercontent.com/17676761/61503562-101ae300-a9d0-11e9-9129-335e9272082b.png)
![image](https://user-images.githubusercontent.com/17676761/61503566-16a95a80-a9d0-11e9-9543-ed970b1f7b04.png)

**Comment by frozenpandaman** [comment]
WOOOWWWW OK, this is going to be a pain to look into… (I think). I can try to figure this out in a few hours. Thanks for the heads up, @466gaming! Could you please send me the relevant battle json so I can debug?

To do that:

1. Find out what battle number this is occurring for (e.g. look at what the one right before this that got uploaded to stat.ink correctly is, and just add 1)

2. Navigate to `https://app.splatoon2.nintendo.net/api/results/#` where the # is the battle number

3. Copy the `cookie` value from your `config.txt`.

3. Use the Chrome extension [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) – or something similar for the browser you use – to edit the `iksm_session` cookie to be the `cookie` value you found before.

4. Refresh the page, select all + copy the text, and make a new [GitHub gist](https://gist.github.com/) (or [pastebin.com](http://pastebin.com/) paste) and link it here!

Thank you so much!

**Comment by 466gaming** [comment]
Thanks for responding so quickly!
The battle json is here:
https://gist.github.com/466gaming/b7efce5cc8a8e4ce993b60c69808b45d

**Comment by frozenpandaman** [comment]
Weird, it's some Python 3-only floating point rounding error when multiplying with the `synergy_mult` (x1.1 in your battle) – `fest_exp` was being set to… 0.9999999999999858 (so, yes, not quite an integer) 😅

Fixed. Thanks!
