### ISSUE TITLE
Unexpected "Too many requests" error using v1.5.3

### ISSUE THREAD

**Issue by e-foley** [frozenpandaman/splatnet2statink#92]
I repeatedly get a "Too many requests" error when running splatnet2statink.py, even despite waiting hours between attempts. I'm running v1.5.3, and I've historically had no issues running this version. I first noticed the issue about three or so days ago. I run on Windows 10.

Command executed:

```
./splatnet2statink.py
```

Output:

```
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Error from the splatnet2statink API:
{
  "error": "Too many requests"
}
```

**Comment by DustinDEV2more** [comment]
Same here

**Comment by frozenpandaman** [comment]
I'm traveling now but will be able to look at this hopefully within the next week. Probably related to #91.
