### ISSUE TITLE
Error from the flagp API: Error 404 (offline or incorrect headers)

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/splatnet2statink#96]
![image](https://user-images.githubusercontent.com/11247506/78733438-d736eb80-791b-11ea-94a2-0e8cd22c78e4.png)

Haven't used splatnet2statink since 4/4 and now it does this, tried deleting config but still the same problem.

**Comment by frozenpandaman** [comment]
Seems to work now. I'm guessing the API was just temporarily offline, same as in #95.
